# Use the official R image from the Docker Hub
FROM rocker/r-ver:4.1.0

# Install necessary Linux packages
RUN apt-get update && apt-get install -y \
    libudunits2-dev \
    libgdal-dev \
    libproj-dev \
    libgeos-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libxml2-dev

# Install R packages
RUN R -e "install.packages(c('lidR', 'raster', 'sf', 'terra', 'e1071'), repos='http://cran.rstudio.com/')"

# Copy the R script into the Docker image
COPY process_lidar_par.R ./process_lidar_par.R

# Set the working directory
WORKDIR .

# Run the R script
CMD ["Rscript", "process_lidar_par.R"]
